# The URL the site will be built for
base_url = "https://glib.org.mx"

default_language = "es_MX"

title = "Grupo Linuxero del Baj√≠o"

taxonomies = [
    {name = "tema", feed = false},
    {name = "autor", feed = false}
]

generate_feed = true

compile_sass = true

[slugify]
paths = "safe"

[extra]
# Put all your custom variables here
default_og_image = "logo.png"
