# The URL the site will be built for
base_url = "https://glib.org.mx/nuevo"

default_language = "es_MX"

taxonomies = [
    {name = "tema", feed = false},
    {name = "autor", feed = false}
]

generate_feed = true
#feed_filename = "backend/geeklog.xml"

compile_sass = true

[slugify]
paths = "safe"

[extra]
# Put all your custom variables here
