# The URL the site will be built for
base_url = "https://glib.org.mx"

default_language = "es"

title = "Grupo Linuxero del Bajío"
description = "Sitio del Grupo Linuxero del Bajío. Software libre para el Bajío."

taxonomies = [
    {name = "tema", feed = false},
    {name = "autor", feed = false}
]

generate_feeds = true
feed_filenames = [ "atom.xml", "rss.xml" ]

compile_sass = true

build_search_index = true

[markdown.highlighting]
theme = "solarized-light"
smart_punctuation = true
render_emoji = true

[slugify]
paths = "safe"

[search]
index_format = "elasticlunr_json"

[extra]
# Put all your custom variables here
default_og_image = "logo.png"
